aws_region    = "us-east-1"
ami_id = "ami-067d1e60475437da2"
instance_type = "t2.micro"
key_name = "turbo-ff-pair"
instance_name = "turbo-ff-sample"
backend_bucket   = "turbo-ff"
state_file_key   = "terraform.tfstate"
backend_region   = "us-east-1"  
